version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "forex"
      POSTGRES_DB: "forex"
  api:
    build: .
    volumes:
      - .:/forex_backend
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres