# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='base',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='target',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='exchangeratehistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.Currency'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('base', 'target')]),
        ),
    ]
